# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/willscott/go-nfs
%global goipath         github.com/willscott/go-nfs
%global commit          e6abde417d5dcd6390ba2d6d08a3cc40e6c64697

%gometa -L -f


%global common_description %{expand:
Golang NFSv3 server.}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           golang-github-willscott-nfs
Version:        0
Release:        %autorelease -p
Summary:        Golang NFSv3 server

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  golang-github-willscott-nfs-client-devel

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

#avoid extra deps
rm -rf example

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
