# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/Azure/azure-sdk-for-go
%global goipath         github.com/Azure/azure-sdk-for-go/sdk/azcore
Version:                1.7.2
%global tag             sdk/azcore/v1.7.2
%global distprefix      %{nil}

%gometa -f


%global common_description %{expand:
Azure SDK for Go - azcore library.}

%global golicenses      NOTICE.txt LICENSE.txt sdk/azcore/LICENSE.txt
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md SUPPORT.md\\\
                        SECURITY.md README.md sdk/azcore/CHANGELOG.md \\\
                        sdk/azcore/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Azure SDK for Go - azcore library

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

# move building library to the root to match goipath
mv sdk/azcore/* .
rm -rf .github documentation eng profile sdk

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# Link path provided by other golang-github-azure-sdk-* packages, as the tests
# require all files in the same path to be able to test using internal libraries
ln -s /usr/share/gocode/src/github.com/Azure/azure-sdk-for-go/sdk/internal _build/src/github.com/Azure/azure-sdk-for-go/sdk/
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
