# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/storj/picobuf
%global goipath         storj.io/picobuf
%global forgeurl        https://github.com/storj/picobuf
Version:                0.0.1

%gometa -f


%global common_description %{expand:
Small replacement for subset of protobuf.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Small replacement for subset of protobuf

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d storj.io/picobuf/internal/sizebench
%endif

%gopkgfiles

%changelog
%autochangelog
