# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/ryszard/goskiplist
%global goipath         github.com/ryszard/goskiplist
%global commit          2dfbae5fcf46374f166f8969cb07e167f1be6273

%gometa -L -f


%global common_description %{expand:
A skip list implementation in Go.}

%global golicenses      LICENSE
%global godocs          AUTHORS CONTRIBUTORS README.markdown

Name:           golang-github-ryszard-goskiplist
Version:        0
Release:        %autorelease -p
Summary:        A skip list implementation in Go

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
