# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/marten-seemann/qtls-go1-18
%global goipath         github.com/marten-seemann/qtls-go1-18
Version:                0.1.1

%gometa

%global common_description %{expand:
Go standard library TLS 1.3 implementation, modified for QUIC. For Go 1.18.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go standard library TLS 1.3 implementation, modified for QUIC. For Go 1.18

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
