# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/zeebo/blake3
%global goipath         github.com/zeebo/blake3
Version:                0.2.3

%gometa

%global common_description %{expand:
Pure Go implementation of BLAKE3 with AVX2 and SSE4.1 acceleration.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Pure Go implementation of BLAKE3 with AVX2 and SSE4.1 acceleration

# Upstream license specification: CC0-1.0
License:        CC0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# require github.com/zeebo/pcg
%gocheck -d internal/alg/compress/compress_sse41 -d internal/alg/hash/hash_avx2
%endif

%gopkgfiles

%changelog
%autochangelog
