# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/go-validator/validator
%global goipath         gopkg.in/validator.v2
%global forgeurl        https://github.com/go-validator/validator
Version:                2.0.1

%gometa -L -f


%global common_description %{expand:
Package validator implements struct field validations.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           golang-gopkg-validator2
Release:        %autorelease
Summary:        Package validator implements struct field validations

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
