# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/henrybear327/Proton-API-Bridge
%global goipath         github.com/henrybear327/Proton-API-Bridge
Version:                1.0.0

%gometa -L -f


%global common_description %{expand:
A third-party, open-source Proton API bridge (mainly focusing on Drive for
now).}

%global golicenses      LICENSE
%global godocs          Documentation.md README.md testcase/empty.txt

Name:           golang-github-henrybear327-proton-api-bridge
Release:        %autorelease
Summary:        A third-party, open-source Proton API bridge (mainly focusing on Drive for now)

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
