# Generated by go2rpm 1.9.0
# Needs fuse.ko loaded
%bcond_with check

# https://github.com/anacrolix/fuse
%global goipath         github.com/anacrolix/fuse
Version:                0.2.0

%gometa -f


%global common_description %{expand:
Bazil.org/fuse - With macOS support and its own import path so replace
directives aren't necessary.}

%global golicenses      LICENSE
%global godocs          examples doc README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Bazil.org/fuse - With macOS support and its own import path so replace directives aren't necessary

License:        BSD and MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
