# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/quic-go/qtls-go1-20
%global goipath         github.com/quic-go/qtls-go1-20
Version:                0.3.0
%global commit          a42b12e32a6d262713531dffeac718b5aa06ed62

%gometa -f


%global common_description %{expand:
Go standard library TLS 1.3 implementation, modified for QUIC. For Go 1.20.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go standard library TLS 1.3 implementation, modified for QUIC.

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
