# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/storj/uplink
%global goipath         storj.io/uplink
%global forgeurl        https://github.com/storj/uplink
Version:                1.10.0

%gometa -f


%global common_description %{expand:
Storj network Go library.}

%global golicenses      LICENSE
%global godocs          examples CODE_OF_CONDUCT.md MAINTAINERS.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Storj network Go library

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
