# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/storj/drpc
%global goipath         storj.io/drpc
%global forgeurl        https://github.com/storj/drpc
Version:                0.0.30

%gometa

%global common_description %{expand:
Drpc is a lightweight, drop-in replacement for gRPC.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Drpc is a lightweight, drop-in replacement for gRPC

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
rm -rf internal/grpccompat

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck -d internal/backcompat -d internal/backcompat/oldservicedefs
%endif

%gopkgfiles

%changelog
%autochangelog
