# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/anacrolix/dms
%global goipath         github.com/anacrolix/dms
Version:                1.5.0

%gometa -f

%global common_description %{expand:
A UPnP DLNA Digital Media Server that includes basic video transcoding.}

%global golicenses      LICENSE
%global godocs          README.rst TODO misc/dms-win32/README.txt

Name:           %{goname}
Release:        %autorelease
Summary:        UPnP DLNA Digital Media Server that includes basic video transcoding

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
