# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/quic-go/quic-go
%global goipath         github.com/quic-go/quic-go
Version:                0.35.1

%gometa -f


%global common_description %{expand:
A QUIC implementation in pure go.}

%global golicenses      LICENSE
%global godocs          docs example SECURITY.md Changelog.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A QUIC implementation in pure go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
