# Generated by go2rpm 1.9.0
# Tests require Recording server
%bcond_with check
%global debug_package %{nil}

# https://github.com/Azure/azure-sdk-for-go
%global goipath         github.com/Azure/azure-sdk-for-go/sdk/storage/azfile
Version:                1.1.1
%global tag             sdk/storage/azfile/v1.1.1
%global distprefix      %{nil}

%gometa -f

%global common_description %{expand:
Azure SDK for Go - azblob library.}

%global golicenses      NOTICE.txt LICENSE.txt sdk/storage/azblob/LICENSE.txt
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md SUPPORT.md\\\
                        SECURITY.md README.md sdk/storage/azblob/CHANGELOG.md \\\
                        sdk/storage/azblob/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Azure SDK for Go - azblob library

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

# move building library to the root to match goipath
mv sdk/storage/azfile/* .
rm -rf .github documentation eng profile sdk

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
