# Generated by go2rpm 1.9.0
# Tests require credentials
%bcond_with check
%global debug_package %{nil}

# https://github.com/Azure/azure-sdk-for-go
%global goipath         github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources
Version:                1.2.0
%global tag             sdk/resourcemanager/resources/armresources/v1.2.0
%global distprefix      %{nil}

%gometa -f

%global common_description %{expand:
Azure SDK for Go - azidentity library.}

%global golicenses      NOTICE.txt LICENSE.txt sdk/azidentity/LICENSE.txt
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md SUPPORT.md\\\
                        SECURITY.md README.md sdk/azidentity/CHANGELOG.md \\\
                        sdk/azidentity/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Azure SDK for Go - resourcemanager/resources/armresources library

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

# move building library to the root to match goipath
mv sdk/resourcemanager/resources/armresources/* .
rm -rf .github documentation eng profile sdk

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
