# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/storj/common
%global goipath         storj.io/common
%global forgeurl        https://github.com/storj/common
%global commit          db6195f39c0dc64aa9e10aeba2e9e3ac1ffa072c

%gometa -f


%global common_description %{expand:
Storj common packages.}

%global golicenses      LICENSE base58/LICENSE
%global godocs          CODE_OF_CONDUCT.md base58/README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p -b 10
Summary:        Storj common packages

License:        ISC and MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# need hello test program?
for test in "TestCompile" \
            "TestFromBuild" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
# rpc: needs network
%gocheck -d rpc -d ranger/httpranger
%endif

%gopkgfiles

%changelog
%autochangelog
