# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/mmcloughlin/avo
%global goipath         github.com/mmcloughlin/avo
Version:                0.4.0

%gometa

%global common_description %{expand:
Generate x86 Assembly with Go.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Generate x86 Assembly with Go

# Upstream license specification: BSD-3-Clause and LGPL-3.0-only
License:        BSD and LGPLv3
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
