# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/henrybear327/go-proton-api
%global goipath         github.com/henrybear327/go-proton-api
Version:                1.0.0

%gometa -L -f


%global common_description %{expand:
Proton API library used by Go-based clients and tools.}

%global golicenses      COPYING_NOTES.md LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           golang-github-henrybear327-proton-api
Release:        %autorelease
Summary:        Proton API library used by Go-based clients and tools

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
