# Generated by go2rpm 1.10.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/willscott/go-nfs-client
%global goipath         github.com/willscott/go-nfs-client
%global commit          b44639837b00f2469a749c154f514524d7397ab7

%gometa -L -f


%global common_description %{expand:
NFS client implementation for Golang.}

%global golicenses      LICENSE_BSD-2.txt NOTICE.txt
%global godocs          README.md example

Name:           golang-github-willscott-nfs-client
Version:        0
Release:        %autorelease -p
Summary:        NFS client implementation for Golang

License:        # FIXME
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
