# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/dropbox/dropbox-sdk-go-unofficial
%global goipath         github.com/dropbox/dropbox-sdk-go-unofficial
Version:                6.0.4

%gometa

%global common_description %{expand:
An unofficial Go SDK for integrating with the Dropbox API v2.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Unofficial Dropbox v2 API SDK for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
