# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/Azure/azure-sdk-for-go
%global goipath         github.com/Azure/azure-sdk-for-go/sdk/internal
Version:                1.3.0
%global tag             sdk/internal/v1.3.0

%gometa -f

%global common_description %{expand:
This repository is for active development of the Azure SDK for Go. For
consumers of the SDK we recommend visiting our public developer docs at:.}

%global golicenses      NOTICE.txt LICENSE.txt sdk/azcore/LICENSE.txt
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md SUPPORT.md\\\
                        SECURITY.md README.md sdk/azcore/CHANGELOG.md \\\
                        sdk/azcore/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        This repository is for active development of the Azure SDK for Go. For consumers of the SDK we recommend visiting our public developer docs at:

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

rm -rf .github documentation eng profile
pushd sdk
rm -rf azcore azidentity containers data keyvault messaging monitor resourcemanager samples security storage template
popd

mv sdk/internal/* .

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
for test in "TestRecordingHTTPClient_Do" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck -d recording
#  -d sdk/internal/poller
%endif

%gopkgfiles

%changelog
%autochangelog
