# Generated by go2rpm 1.8.1
%bcond_without check
%bcond_with bootstrap
%global debug_package %{nil}

# https://github.com/open-telemetry/opentelemetry-go-contrib
%global goipath         go.opentelemetry.io/contrib
%global forgeurl        https://github.com/open-telemetry/opentelemetry-go-contrib
Version:                1.10.0

%gometa

%global common_description %{expand:
Collection of extensions for OpenTelemetry-Go.}

%global golicenses      LICENSE
%global godocs          README.md RELEASING.md CHANGELOG.md CONTRIBUTING.md

Name:           %{goname}
Release:        %autorelease
Summary:        Collection of extensions for OpenTelemetry-Go

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
rm -rfv instrumentation/github.com/astaxie/beego/
# examples are not packaged
rm -rvf propagators/opencensus/examples
# drop until github.com/GoogleCloudPlatform/opentelemetry-operations-go is packaged
rm -rvf detectors/gcp

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck -t instrumentation
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
