# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/storj/common
%global goipath         storj.io/common
%global forgeurl        https://github.com/storj/common
%global commit          ec9c16f58d50effc12f42543990bdd69a332d407

%gometa

%global common_description %{expand:
Storj common packages.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md base58/README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Storj common packages

License:        ISC and MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
# Required due to breaking change in golang-github-lucas-clemente-quic-0.27
sed -i "s|quic.Session|quic.Connection|" rpc/quic/*.go

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# TestWhatsMyIP requires network
for test in "TestLookupNodeAddress_Host" "TestLookupNodeAddress_HostAndPort" "TestCompile" "TestFromBuild"	\
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
