# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/rclone/rclone
%global goipath         github.com/rclone/rclone
Version:                1.58.1

%gometa

%global common_description %{expand:
Rclone is a command line program to sync files and directories to and
from various cloud services.}

# This package uses gold. Tell package-notes implementation about this.
%global _package_note_linker gold

Name:           rclone
Release:        %autorelease
Summary:        Rsync for cloud storage

License:        MIT
URL:            https://rclone.org/
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
sed -i "s|github.com/putdotio/go-putio/putio|github.com/putdotio/go-putio|" $(find . -name "*.go")
#sed -i "s|github.com/rclone/ftp|github.com/jlaffaye/ftp|" $(find . -name "*.go")
rm -rf backend/storj
sed -i "s|	_ \"github.com/rclone/rclone/backend/storj\"||" backend/all/all.go
%generate_buildrequires
%go_generate_buildrequires

%build
LDFLAGS="-X github.com/ncw/rclone/fs.Version=v%{version} "
%gobuild -o %{gobuilddir}/bin/rclone %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -Dpm 0644 ./rclone.1 %{buildroot}%{_mandir}/man1/rclone.1

%if %{with check}
%check
%gocheck -d backend/crypt
%endif

%files
%license COPYING
%doc MAINTAINERS.md MANUAL.html RELEASE.md CONTRIBUTING.md MANUAL.md README.md
%doc docs/
%{_bindir}/rclone
%{_mandir}/man1/rclone.1*
%gopkgfiles

%changelog
%autochangelog
